spring:
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url:
      username:
      password:
      minimum-idle: 1
      maximum-pool-size: 15
      auto-commit: false
